#! /bin/sh

### BEGIN INIT INFO
# Provides:		connect4g
# Required-Start:	$syslog
# Required-Stop:	$syslog
# Default-Start:	2 3 4 5
# Default-Stop:		
# Short-Description:	connect4g
### END INIT INFO

set -e

test -x /usr/local/bin/connect4g.sh || exit 0

umask 022


. /lib/lsb/init-functions



export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"

case "$1" in

  start)
	log_daemon_msg "Starting connect4g Daemon" || true
	if start-stop-daemon --start --oknodo -b --exec /usr/local/bin/connect4g.sh ; then
	    log_end_msg 0 || true
	else
	    log_end_msg 1 || true
	fi
	;;

  stop)
	log_daemon_msg "Stoping connect4g Daemon" || true
    killall connect4g.sh
	;;

  restart)
	;;

  status)
	;;

  *)
	log_action_msg "Usage: /etc/init.d/connect4g {start|stop|restart|status}" || true
	exit 1
esac

exit 0
